name: flutter_snackbox
description: show snackBar made easy, display snackBar without buildContext with pure dart code.
version: 2.0.0
homepage: https://github.com/swarajkumarsingh/flutter_snackbox

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
